language: ruby
rvm: 1.9.3
before_install: cp config/database.yml.default config/database.yml
before_script:
  - rake db:create
  - rake db:migrate
notifications:
  irc: "irc.freenode.org#winged-monkey"
