# The list of mock launchables
- !ruby/object:Providers::Mock::MockLaunchable
  id: 1
  name: Mock Launchable 1
  description: Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
  cost: 0.09
  wm_state: ACTIVE
- !ruby/object:Providers::Mock::MockLaunchable
  id: 2
  name: Mock Launchable 2 with a longer name
  description: Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
  cost: 0.03
  wm_state: ACTIVE
- !ruby/object:Providers::Mock::MockLaunchable
  id: 3
  name: Mock Launchable 3
  description: Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
  cost: 0.09
  wm_state: ACTIVE
- !ruby/object:Providers::Mock::MockLaunchable
  id: 4
  name: Mock Launchable 4
  description: Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
  cost: 0.03
  wm_state: ACTIVE