---
http_interactions:
- request:
    method: get
    uri: http://username:password@conductor.test.com/api/pools/1/deployments.xml
    body:
      encoding: US-ASCII
      string: ''
    headers:
      accept:
      - ! '*/*'
      user-agent:
      - Ruby
      authorization:
      - Basic dXNlcm5hbWU6cGFzc3dvcmQ=
  response:
    status:
      code: 401
      message: Unauthorized
    headers:
      x-request-id:
      - 6740808c635a42453e3c7bd0b83c787a
      content-type:
      - application/xml; charset=utf-8
      set-cookie:
      - _session_id=5a658e1826f18589b32ee3e3bcb5de5b; path=/; expires=Wed, 12-Dec-2012
        21:16:27 GMT; HttpOnly
      cache-control:
      - no-cache
      x-runtime:
      - '0.297176'
      x-ua-compatible:
      - IE=Edge
      content-length:
      - '1'
      connection:
      - keep-alive
      server:
      - thin 1.3.1 codename Triple Espresso
    body:
      encoding: US-ASCII
      string: ! ' '
    http_version: '1.1'
  recorded_at: Wed, 12 Dec 2012 21:01:27 GMT
- request:
    method: get
    uri: http://admin:password@conductor.test.com/api/pools/1/deployments.xml
    body:
      encoding: US-ASCII
      string: ''
    headers:
      accept:
      - ! '*/*'
      user-agent:
      - Ruby
      authorization:
      - Basic YWRtaW46cGFzc3dvcmQ=
  response:
    status:
      code: 200
      message: OK
    headers:
      x-request-id:
      - 477f2f23e1d000aee63f1947ec020316
      content-type:
      - application/xml; charset=utf-8
      set-cookie:
      - _session_id=0471c5d298b5e88521e28fca434212c2; path=/; expires=Wed, 12-Dec-2012
        21:19:07 GMT; HttpOnly
      cache-control:
      - max-age=0, private, must-revalidate
      x-runtime:
      - '0.662180'
      x-ua-compatible:
      - IE=Edge
      content-length:
      - '5931'
      etag:
      - ! '"14ed512a47b6bcafb6eb231ca754f99f"'
      connection:
      - keep-alive
      server:
      - thin 1.3.1 codename Triple Espresso
    body:
      encoding: US-ASCII
      string: ! "<deployments href='http://conductor.test.com/api/pools/1/deployments'>\n
        \ <deployment href='http://conductor.test.com/api/deployments/12' id='12'>\n
        \   <name>10</name>\n    <pool href='http://conductor.test.com/api/pools/1'
        id='1'></pool>\n    <uuid>4c9844f8-d048-11e1-ac86-001558c8816e</uuid>\n    <scheduled_for_deletion>false</scheduled_for_deletion>\n
        \ </deployment>\n  <deployment href='http://conductor.test.com/api/deployments/13'
        id='13'>\n    <name>11</name>\n    <pool href='http://conductor.test.com/api/pools/1'
        id='1'></pool>\n    <uuid>11a18bf6-d049-11e1-ac86-001558c8816e</uuid>\n    <scheduled_for_deletion>false</scheduled_for_deletion>\n
        \ </deployment>\n  <deployment href='http://conductor.test.com/api/deployments/14'
        id='14'>\n    <name>12</name>\n    <pool href='http://conductor.test.com/api/pools/1'
        id='1'></pool>\n    <uuid>79c394a4-d049-11e1-ac86-001558c8816e</uuid>\n    <scheduled_for_deletion>false</scheduled_for_deletion>\n
        \ </deployment>\n  <deployment href='http://conductor.test.com/api/deployments/22'
        id='22'>\n    <name>17</name>\n    <pool href='http://conductor.test.com/api/pools/1'
        id='1'></pool>\n    <uuid>ad543206-f763-11e1-be29-001558c8816e</uuid>\n    <scheduled_for_deletion>false</scheduled_for_deletion>\n
        \ </deployment>\n  <deployment href='http://conductor.test.com/api/deployments/23'
        id='23'>\n    <name>18</name>\n    <pool href='http://conductor.test.com/api/pools/1'
        id='1'></pool>\n    <uuid>0001b210-f78e-11e1-be29-001558c8816e</uuid>\n    <scheduled_for_deletion>false</scheduled_for_deletion>\n
        \ </deployment>\n  <deployment href='http://conductor.test.com/api/deployments/24'
        id='24'>\n    <name>19</name>\n    <pool href='http://conductor.test.com/api/pools/1'
        id='1'></pool>\n    <uuid>a8def23a-f78e-11e1-be29-001558c8816e</uuid>\n    <scheduled_for_deletion>false</scheduled_for_deletion>\n
        \ </deployment>\n  <deployment href='http://conductor.test.com/api/deployments/2'
        id='2'>\n    <name>2</name>\n    <pool href='http://conductor.test.com/api/pools/1'
        id='1'></pool>\n    <uuid>b188dce0-cabe-11e1-86f4-001558c8816e</uuid>\n    <scheduled_for_deletion>false</scheduled_for_deletion>\n
        \ </deployment>\n  <deployment href='http://conductor.test.com/api/deployments/25'
        id='25'>\n    <name>20</name>\n    <pool href='http://conductor.test.com/api/pools/1'
        id='1'></pool>\n    <uuid>a7142f78-f78f-11e1-be29-001558c8816e</uuid>\n    <scheduled_for_deletion>false</scheduled_for_deletion>\n
        \ </deployment>\n  <deployment href='http://conductor.test.com/api/deployments/26'
        id='26'>\n    <name>21</name>\n    <pool href='http://conductor.test.com/api/pools/1'
        id='1'></pool>\n    <uuid>6d4b22ae-f791-11e1-be29-001558c8816e</uuid>\n    <scheduled_for_deletion>false</scheduled_for_deletion>\n
        \ </deployment>\n  <deployment href='http://conductor.test.com/api/deployments/27'
        id='27'>\n    <name>22</name>\n    <pool href='http://conductor.test.com/api/pools/1'
        id='1'></pool>\n    <uuid>f2bf16a2-f791-11e1-be29-001558c8816e</uuid>\n    <scheduled_for_deletion>false</scheduled_for_deletion>\n
        \ </deployment>\n  <deployment href='http://conductor.test.com/api/deployments/3'
        id='3'>\n    <name>3</name>\n    <pool href='http://conductor.test.com/api/pools/1'
        id='1'></pool>\n    <uuid>011eeabe-caca-11e1-86f4-001558c8816e</uuid>\n    <scheduled_for_deletion>false</scheduled_for_deletion>\n
        \ </deployment>\n  <deployment href='http://conductor.test.com/api/deployments/4'
        id='4'>\n    <name>4</name>\n    <pool href='http://conductor.test.com/api/pools/1'
        id='1'></pool>\n    <uuid>425bc520-cd03-11e1-86f4-001558c8816e</uuid>\n    <scheduled_for_deletion>false</scheduled_for_deletion>\n
        \ </deployment>\n  <deployment href='http://conductor.test.com/api/deployments/9'
        id='9'>\n    <name>7</name>\n    <pool href='http://conductor.test.com/api/pools/1'
        id='1'></pool>\n    <uuid>1fe492ac-d045-11e1-ac86-001558c8816e</uuid>\n    <scheduled_for_deletion>false</scheduled_for_deletion>\n
        \ </deployment>\n  <deployment href='http://conductor.test.com/api/deployments/11'
        id='11'>\n    <name>9</name>\n    <pool href='http://conductor.test.com/api/pools/1'
        id='1'></pool>\n    <uuid>88ab306e-d047-11e1-ac86-001558c8816e</uuid>\n    <scheduled_for_deletion>false</scheduled_for_deletion>\n
        \ </deployment>\n  <deployment href='http://conductor.test.com/api/deployments/1'
        id='1'>\n    <name>Deployable1</name>\n    <pool href='http://conductor.test.com/api/pools/1'
        id='1'></pool>\n    <uuid>9d7a771c-caba-11e1-86f4-001558c8816e</uuid>\n    <scheduled_for_deletion>false</scheduled_for_deletion>\n
        \ </deployment>\n  <deployment href='http://conductor.test.com/api/deployments/56'
        id='56'>\n    <name>ec2-medium-test</name>\n    <pool href='http://conductor.test.com/api/pools/1'
        id='1'></pool>\n    <uuid>f2ecbd96-0411-11e2-84f4-001558c8816e</uuid>\n    <scheduled_for_deletion>false</scheduled_for_deletion>\n
        \ </deployment>\n  <deployment href='http://conductor.test.com/api/deployments/55'
        id='55'>\n    <name>ec2-small-test</name>\n    <pool href='http://conductor.test.com/api/pools/1'
        id='1'></pool>\n    <uuid>b4a6fea2-0411-11e2-84f4-001558c8816e</uuid>\n    <scheduled_for_deletion>false</scheduled_for_deletion>\n
        \ </deployment>\n  <deployment href='http://conductor.test.com/api/deployments/53'
        id='53'>\n    <name>ec2-test-1</name>\n    <pool href='http://conductor.test.com/api/pools/1'
        id='1'></pool>\n    <uuid>9741c746-040e-11e2-84f4-001558c8816e</uuid>\n    <scheduled_for_deletion>false</scheduled_for_deletion>\n
        \ </deployment>\n  <deployment href='http://conductor.test.com/api/deployments/54'
        id='54'>\n    <name>medium-ec2-test</name>\n    <pool href='http://conductor.test.com/api/pools/1'
        id='1'></pool>\n    <uuid>91c70104-040f-11e2-84f4-001558c8816e</uuid>\n    <scheduled_for_deletion>false</scheduled_for_deletion>\n
        \ </deployment>\n  <deployment href='http://conductor.test.com/api/deployments/59'
        id='59'>\n    <name>small-ec2</name>\n    <pool href='http://conductor.test.com/api/pools/1'
        id='1'></pool>\n    <uuid>7baf962e-0419-11e2-8da4-001558c8816e</uuid>\n    <scheduled_for_deletion>false</scheduled_for_deletion>\n
        \ </deployment>\n</deployments>\n"
    http_version: '1.1'
  recorded_at: Wed, 12 Dec 2012 21:17:07 GMT
recorded_with: VCR 2.3.0
